### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by HackMeMan** [Project-Genoa/Vienna#1]
It has no readme and isn't referenced in any other project. What exactly is "Vienna", and how is it related to Project Genoa?

**Comment by Lamerdagrossa2010** [comment]
Vienna is the api server re creation for minecraft earth

Its made by @micheal65536 and now it runs on docker.
Gotta be honest m quintino everything related to mce

**Comment by HackMeMan** [comment]
Isn't that the guy who made Project Wildflower?

**Comment by Lamerdagrossa2010** [comment]
> Isn't that the guy who made Project Wildflower?

Yep he is
